name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  TF_WORKING_DIR: envs/dev
  AWS_REGION: eu-west-2

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: eu-west-2
      TF_VAR_project_name: terraform-aws-platform-infra
      TF_VAR_environment: dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials using OIDC
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::361769572669:role/github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform format check
        run: terraform fmt -check -recursive
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform plan
        if: github.ref == 'refs/heads/main'
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}